version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheusContainer
    volumes:
      - /var/lib/jenkins/workspace/kaddem/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafanaContainer
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  
      - GF_SECURITY_ADMIN_USER=adminn
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge
